console.log("Hello world");
var found = true;
var grade = 88.6;
var firstName = "Darko";
var lastName = 'Darkonnen';
found = false;
grade = 100;
firstName = "Darkonnen";
lastName = true;
// console.log(found + " " + grade + " " + firstName + " " + lastName);
console.log("Hi " + firstName);
